### PR TITLE
Missing import statement

### PR DESCRIPTION
**Pull request by Gmaj7**

### CODE REVIEW

**Comment by ExplodingCabbage** [comment]
@djacobs, it would be helpful to people trying to understand the current state of this project (and whether any feature they're planning on PRing has already been implemented by someone else) if you'd close the obsolete pull requests like this one. I'm gradually going through the open pull requests to see what state they're in and what should be done with them, and in most cases the answer seems to be that they should be closed.

**Comment by djacobs** [comment]
@ExplodingCabbage Yes - some gardening is in order for sure. But in general if I haven't vetted code or someone hasn't poked me, I'm very conservative about pull requests - the library is widely deployed and part of that is that it doesn't change much!

But we do need python 3 support and Apple's new APNS APIs to be on PyPi sooner than later.

**Comment by ExplodingCabbage** [comment]
@djacobs Conservatism is reasonable, but culling obsolete requests doesn't violate that conservatism. This is obsolete.

**Comment by ExplodingCabbage** [comment]
FYI, I'm planning to gradually look over all the pull requests on this repo and comment on what I think needs doing with them, so you'll have at least one additional pair of eyes on everything, for whatever it's worth. My endgame is to get everything that's obsolete or bullshit closed, get everything that has value merged, and then implement the new HTTP/2 API.

**Comment by djacobs** [comment]
Thank you, I appreciate it

**Pull request closed without merging**
