### PR TITLE
add title and subtile params for iOS 10

### PR DESCRIPTION
**Pull request by ChaosTong**
in iOS 10 you can use **title** and **subtitle** to make your words like this

### CODE REVIEW

**Comment by chadham** [comment]
Can we get this pulled please? Thanks

**Comment by ChaosTong** [comment]
@chadham sure

**Comment by chadham** [comment]
Hi, am not familiar how GitHub works. Will Jacobs pull your update and
commit in his branch?

I'd like to use the title and subtitle in my notifications.

Thanks.

**Comment by ChaosTong** [comment]
@chadham i have no idea about that. if you want use this feature you can just change the source code in your project, just 9 lines change you can see it in files changed

**Comment by chadham** [comment]
I tried that already, but Im not able to build/install via my raspberry pi. Says apyns.py file has null characters - it won't let me compile the original file due to the same error (so Im sure I didn't introduce it by editing in vi).

**Comment by ChaosTong** [comment]
@chadham you can use it by source code rather than install as module, you did like this. or you install it then change the installed code

**Comment by chadham** [comment]
Confirmed it works. Thanks very much.

**Comment by r4m** [comment]
+1 for pulling it thx

**Pull request merged**
